In [71]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier

data = {
    "study_hours": [1, 2, 3, 4, 5, 6, 7, 8],
    "attendance": [50, 55, 60, 80, 60, 76, 5, 80],
    "pass_fail": [0, 0, 0, 1, 0, 1, 1, 1,]
}

df = pd.DataFrame(data)

# 입력값과 정답 분리
X = df[["study_hours", "attendance"]]
y = df["pass_fail"]

model = DecisionTreeClassifier(random_state=42)
model.fit(X, y)

print("데이터 준비 완료")
print(f"학생 수: {len(df)}명") # 학생 수: %%명

데이터 준비 완료
학생 수: 8명

 # 모델 정확도

 - 학습에 사용한 데이터로 정확도 확인

In [72]:
accuracy = model.score(X, y)
print("모델 정확도:", accuracy) # 0~1 표시됨 -> 0~100%
print(f"모델 정확도 퍼센트:{accuracy * 100}%")

모델 정확도: 1.0
모델 정확도 퍼센트:100.0%

In [73]:
# 모델이 어떤 예측을 했는지 확인
predictions = model.predict(X)

# Columns - 공부시간, 출석률, 실제, 예측, 결과
#zip() = zip([1,2,3], [4,5,6]) => (1,4), (2,5), (3,6)
result = pd.DataFrame({
    "공부시간": X["study_hours"].values,
    "출석률": X["attendance"].values,
    "pass_fail": y.values,
    "예측": predictions,
    "결과": ["O" if a == p else "X" for a, p in zip(y, predictions)]
})

result

   공부시간  출석률  pass_fail  예측 결과
0     1   50          0   0  O
1     2   55          0   0  O
2     3   60          0   0  O
3     4   80          1   1  O
4     5   60          0   0  O
5     6   76          1   1  O
6     7    5          1   1  O
7     8   80          1   1  O

# 딕셔너리

Key-Value 한쌍으로 이루어진 집합(자료형)

- 리스트 -> 번호표가 있는 사물함 (0번, 1번, 2번, ...)
- Dictionary -> 이름표가 있는 사물함 (학번, 이름, 학년)

In [74]:
# 리스트
student_list = ["kim", 20, 50]
print(f"리스트에서 이름 출력: {student_list[0]}")

#딕셔너리
student_dict = {"name": "kim", "age": 20, "score": 50}
print(f"딕셔너리에서 이름 출력: {student_dict["name"]}")

리스트에서 이름 출력: kim
딕셔너리에서 이름 출력: kim

In [75]:
person = {
    "name": "아무개",
    "age": 20,
    "major": "AI응용프로그래밍"
}

#전체 출력
print(person)

#나이
print(person["age"])

#과목
print(person["major"])

{'name': '아무개', 'age': 20, 'major': 'AI응용프로그래밍'}
20
AI응용프로그래밍

In [76]:
person["age"] = 21
print(person["age"], person)

# 성별 추가
person["gender"] = "male"
print(person)

# 성별 삭제
del person["gender"]
print(person)

21 {'name': '아무개', 'age': 21, 'major': 'AI응용프로그래밍'}
{'name': '아무개', 'age': 21, 'major': 'AI응용프로그래밍', 'gender': 'male'}
{'name': '아무개', 'age': 21, 'major': 'AI응용프로그래밍'}

# 문제
- 사과, 바나나, 포도는 각 1000원, 2000원, 3000원이다.
    - 딕셔너리 로그 출력
- 사과의 가격을 10% 할인하고 바나나는 13% 인상하였을 때,
    - Python 코드로 작성
- 사과, 바나나, 포도의 가격표를 표시하세요. 
    - 로그 출력 (DataFrame 사용)

In [77]:
fruit = {
    "사과": 1000,
    "바나나": 2000,
    "포도": 3000,
}

print(fruit)

fruit["사과"] *= 1.1
fruit["바나나"] *= 1.3

print(f"사과:{fruit["사과"]}, 바나나:{fruit["바나나"]}")

df = pd.DataFrame(list(fruit.items()), columns=["과일", "가격"])

print(df)

{'사과': 1000, '바나나': 2000, '포도': 3000}
사과:1100.0, 바나나:2600.0
    과일      가격
0   사과  1100.0
1  바나나  2600.0
2   포도  3000.0

# 딕셔너리와 반복문 함께 사용

In [78]:
scores = {
    "국어": 88,
    "수학": 76,
    "영어": 92
}

# 로그 출력 ---------
# 국어: 88점
# 수학: 76점
# 영어: 92점

for subject, score in scores.items():
    print(f"{subject}: {score}점")

국어: 88점
수학: 76점
영어: 92점

In [79]:
# 80점 이상인 과목만 출력


for subject, score in scores.items():
    if score >= 80:
        print(f"80점 이상인 과목: {subject}")

80점 이상인 과목: 국어
80점 이상인 과목: 영어

In [80]:
data = {
    "study_hours": [1, 2, 3, 4, 5, 6, 7, 8],
    "attendance": [50, 55, 60, 80, 60, 76, 5, 80],
    "pass_fail": [0, 0, 0, 1, 0, 1, 1, 1,]
}

df = pd.DataFrame(data)
df

   study_hours  attendance  pass_fail
0            1          50          0
1            2          55          0
2            3          60          0
3            4          80          1
4            5          60          0
5            6          76          1
6            7           5          1
7            8          80          1

In [81]:
# 상위 3줄만 보기
df.head(3)

   study_hours  attendance  pass_fail
0            1          50          0
1            2          55          0
2            3          60          0

In [82]:
# 기본 통계 보기
# count - 데이터 개수
# mean - 평균값
# std - 표준편차 (평균에서 얼마나 퍼져있는지, 클수록 편차가 큼)
# min - 최솟값
# 25% - 하위 25%
# 50% - 중앙값
# 75 - 상위 25%
# max - 최댓값
df.describe()

       study_hours  attendance  pass_fail
count      8.00000    8.000000   8.000000
mean       4.50000   58.250000   0.500000
std        2.44949   24.440891   0.534522
min        1.00000    5.000000   0.000000
25%        2.75000   53.750000   0.000000
50%        4.50000   60.000000   0.500000
75%        6.25000   77.000000   1.000000
max        8.00000   80.000000   1.000000

In [83]:
# 조건으로 데이터 골라내기
high_attendance = df[df["attendance"] >= 70]
#high_attendance

# 합격한 학생만 출력
pass_student = df[df["pass_fail"] == 1]
pass_student

   study_hours  attendance  pass_fail
3            4          80          1
5            6          76          1
6            7           5          1
7            8          80          1

# 날씨 예측

In [84]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier

In [85]:
# 데이터 준비
weather_data = {
    "clouds":   [10, 20, 30, 50, 60, 70, 80, 90, 95, 40],
    "humidity": [30, 35, 40, 55, 65, 70, 80, 85, 90, 45],
    "umbrella": [0 , 0 , 0 , 0 , 1 , 1 , 1 , 1 , 1 , 0 ]
}

weather_df = pd.DataFrame(weather_data)
weather_df

   clouds  humidity  umbrella
0      10        30         0
1      20        35         0
2      30        40         0
3      50        55         0
4      60        65         1
5      70        70         1
6      80        80         1
7      90        85         1
8      95        90         1
9      40        45         0

In [86]:
# 입력값과 정답 분리
X_weather = weather_df[["clouds", "humidity"]]
y_weather = weather_df["umbrella"]

print("입력값과 정답 분리 완료")

입력값과 정답 분리 완료

In [87]:
# 모델 만들기 + 학습
weather_model = DecisionTreeClassifier(random_state=42)
weather_model.fit(X_weather, y_weather)
print("모델 학습 완료")

모델 학습 완료

In [ ]:
# 예측하기
test_weather = pd.DataFrame([
    [20, 35],
    [55, 60],
    [85, 88]
], columns=["clouds", "humidity"])

predictions = weather_model.predict(test_weather)
predictions

# 로그 출력
# 구름 ?%, 습도 ?%

array([0, 0, 1])

## 문제

아래 로그 개별 출력
- 구름 ?%, 습도 ?% -> 우산 필요|불필요
    - 예시) 구름 20%, 습도 35% -> 우산 불필요

In [89]:
# 모델 정확도 구하기

acc = weather_model.score(X_weather, y_weather)
print(f"모델 정확도: {acc * 100}%")

모델 정확도: 100.0%

In [ ]:
# 모델 정확도 낮추기
# 애매한 데이터를 포함한 날씨 데이터
 
messy_data = {
    "clouds":   [10, 20, 55, 55, 60, 70, 80, 90],
    "humidity": [30, 35, 60, 60, 65, 70, 80, 85],
    "umbrella": [0 , 0 , 0 , 1 , 1 , 1 , 1 , 1],
}

messy_df = pd.DataFrame(messy_data)

X_messy = messy_df[["clouds", "humidity"]]
y_messy = messy_df["umbrella"]

messy_model = DecisionTreeClassifier(random_state=42)
messy_model.fit(X_messy, y_messy)

messy_acc = messy_model.score(X_messy, y_messy)
print(f"애매한 데이터 모델 정확도: {messy_acc * 100}")

messy_pred = messy_model.predict(X_messy)

result = pd.DataFrame({
    "구름": X_messy["clouds"].values,
    "습도": X_messy["humidity"].values,
    "실제": y_messy.values,
    "예측": messy_pred,
    "결과": ["O" if a == p else "X" for a, p in zip(y_messy, messy_pred)]
})

애매한 데이터 모델 정확도: 87.5